# Site settings
title: Jepz - My development blog
email: your-email@domain.com
description: "
 My developer blog where i will post most of the things that I work on, problems as findings."
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://jepz.one"
twitter_username: jeppsonone
github_username:  jepz

# Build settings
markdown: kramdown
baseurl: /jekyllblog
