
title: Jepz - My road towards Fullstack.js developer
email: your-email@domain.com
description: "
 My developer blog where i will post most of the things that I work on, problems as findings."
baseurl: ""
url: "http://www.jepz.io"
twitter_username: jeppsonone
github_username:  jepz
collections:
  - projects:
    output: true
    permalink: /projects/:path/


markdown: kramdown
url: "http://jepz.io"
